"""empty message

Revision ID: 793f5dcff972
Revises: dd57d6665121
Create Date: 2017-02-20 23:03:07.197487

"""

# revision identifiers, used by Alembic.
revision = '793f5dcff972'
down_revision = 'dd57d6665121'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_attachment',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('lead_id', sa.String(length=100), nullable=False),
    sa.Column('attachment', postgresql.JSON(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_management.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_attachment')
    ### end Alembic commands ###
